# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4ENDIFbsoJBLHzLlratmL55rUyzdI4s
"""

import streamlit as st
import pandas as pd
import altair as alt
from supabase import create_client
from postgrest.exceptions import APIError

# --- KONFIGURACJA ---
st.set_page_config(page_title="Magazyn Pro", page_icon="🏭", layout="wide")

try:
    url = st.secrets["SUPABASE_URL"]
    key = st.secrets["SUPABASE_KEY"]
except FileNotFoundError:
    st.error("Brak kluczy API!")
    st.stop()

@st.cache_resource
def init_connection():
    return create_client(url, key)

supabase = init_connection()

# --- FUNKCJE BAZY DANYCH ---

def pobierz_dane_df():
    """Pobiera dane i od razu zamienia je na Pandas DataFrame (do wykresów)."""
    try:
        response = supabase.table('magazyn').select("*").execute()
        df = pd.DataFrame(response.data)
        if not df.empty:
            # Obliczamy wartość każdego towaru (ilość * cena)
            df['wartosc_calkowita'] = df['ilosc'] * df['cena']
        return df
    except APIError as e:
        st.error(f"Błąd bazy: {e.message}")
        return pd.DataFrame()

def dodaj_produkt(nazwa, kategoria, opis, ilosc, cena, min_stan):
    dane = {
        "nazwa": str(nazwa),
        "kategoria": str(kategoria),
        "opis": str(opis),
        "ilosc": int(ilosc),
        "cena": float(cena),
        "min_stan": int(min_stan)
    }
    try:
        supabase.table('magazyn').insert(dane).execute()
        return True, "Dodano pomyślnie."
    except APIError as e:
        return False, f"Błąd: {e.message}"

def aktualizuj_stan(id_produktu, zmiana):
    try:
        # Pobieramy obecny stan
        res = supabase.table('magazyn').select("ilosc").eq("id", id_produktu).single().execute()
        if not res.data: return False, "Brak towaru."

        nowa_ilosc = res.data['ilosc'] + zmiana
        if nowa_ilosc < 0: return False, "Brak wystarczającej ilości towaru!"

        supabase.table('magazyn').update({"ilosc": nowa_ilosc}).eq("id", id_produktu).execute()
        return True, f"Nowy stan: {nowa_ilosc}"
    except APIError as e:
        return False, str(e)

# --- INTERFEJS ---

st.title("🏭 Centrum Zarządzania Magazynem")

# Menu główne
tab_dash, tab_lista, tab_operacje, tab_nowy = st.tabs([
    "📈 Dashboard i Wykresy",
    "📋 Lista i Alarmy",
    "🔄 Dostawa / Wydanie",
    "➕ Dodaj Produkt"
])

# Pobieramy dane raz na początku odświeżenia strony
df = pobierz_dane_df()

# --- ZAKŁADKA 1: DASHBOARD (WYKRESY) ---
with tab_dash:
    if not df.empty:
        # --- KPI (Kluczowe Wskaźniki) ---
        total_sztuk = df['ilosc'].sum()
        total_wartosc = df['wartosc_calkowita'].sum()
        alarmy_count = df[df['ilosc'] <= df['min_stan']].shape[0]

        col1, col2, col3 = st.columns(3)
        col1.metric("📦 Łącznie sztuk", f"{total_sztuk}")
        col2.metric("💰 Wartość magazynu", f"{total_wartosc:.2f} PLN")
        col3.metric("⚠️ Niskie stany", f"{alarmy_count}", delta_color="inverse")

        st.divider()

        # --- WYKRESY ---
        c1, c2 = st.columns(2)

        with c1:
            st.subheader("💰 Wartość w kategoriach")
            # Agregacja danych
            df_kat = df.groupby('kategoria')['wartosc_calkowita'].sum().reset_index()

            # Wykres kołowy (Donut chart) przy użyciu Altair
            base = alt.Chart(df_kat).encode(theta=alt.Theta("wartosc_calkowita", stack=True))
            pie = base.mark_arc(outerRadius=120).encode(
                color="kategoria",
                order=alt.Order("wartosc_calkowita", sort="descending"),
                tooltip=["kategoria", "wartosc_calkowita"]
            )
            text = base.mark_text(radius=140).encode(
                text="wartosc_calkowita",
                order=alt.Order("wartosc_calkowita", sort="descending")
            )
            st.altair_chart(pie + text, use_container_width=True)

        with c2:
            st.subheader("📊 Ilości produktów")
            st.bar_chart(df, x="nazwa", y="ilosc", color="kategoria")

    else:
        st.info("Dodaj pierwsze produkty, aby zobaczyć wykresy.")

# --- ZAKŁADKA 2: LISTA I ALARMY ---
with tab_lista:
    st.header("Szczegółowy stan magazynowy")

    if not df.empty:
        # Kolorowanie wierszy (Low code trick w Pandas Styler)
        def highlight_low_stock(row):
            if row['ilosc'] <= row['min_stan']:
                return ['background-color: #ffcccc'] * len(row)
            return [''] * len(row)

        # Wybieramy kolumny do wyświetlenia
        view_df = df[['id', 'nazwa', 'kategoria', 'ilosc', 'min_stan', 'cena', 'wartosc_calkowita', 'opis']]

        # Aplikujemy style (czerwone tło dla niskich stanów)
        st.dataframe(
            view_df.style.apply(highlight_low_stock, axis=1).format({"cena": "{:.2f} zł", "wartosc_calkowita": "{:.2f} zł"}),
            use_container_width=True,
            hide_index=True
        )

        # Szybki filtr alarmowy
        if st.checkbox("Pokaż tylko produkty, które trzeba domówić"):
            st.dataframe(df[df['ilosc'] <= df['min_stan']])

    else:
        st.warning("Baza jest pusta.")

# --- ZAKŁADKA 3: OPERACJE ---
with tab_operacje:
    st.header("Szybkie przyjęcia i wydania")
    if not df.empty:
        col_list, col_action = st.columns([2, 1])

        with col_list:
            # Selectbox z wyszukiwaniem
            opcje = {f"{row['nazwa']} (Stan: {row['ilosc']})": row['id'] for i, row in df.iterrows()}
            wybrany_klucz = st.selectbox("Wybierz produkt:", list(opcje.keys()))
            wybrane_id = opcje[wybrany_klucz]

        with col_action:
            ilosc_op = st.number_input("Liczba sztuk", min_value=1, value=1)

            c_plus, c_minus = st.columns(2)
            if c_plus.button("➕ Przyjmij", use_container_width=True):
                ok, msg = aktualizuj_stan(wybrane_id, ilosc_op)
                if ok: st.success(msg); st.rerun()
                else: st.error(msg)

            if c_minus.button("➖ Wydaj", use_container_width=True):
                ok, msg = aktualizuj_stan(wybrane_id, -ilosc_op)
                if ok: st.success(msg); st.rerun()
                else: st.error(msg)

# --- ZAKŁADKA 4: NOWY PRODUKT ---
with tab_nowy:
    st.header("Rejestracja nowego asortymentu")
    with st.form("add_prod"):
        c1, c2 = st.columns(2)
        with c1:
            n_nazwa = st.text_input("Nazwa")
            n_kat = st.selectbox("Kategoria", ["Elektronika", "Spożywcze", "Budowlane", "Chemia", "Biurowe"])
            n_opis = st.text_area("Opis")
        with c2:
            n_ilosc = st.number_input("Ilość startowa", 0)
            n_cena = st.number_input("Cena zakupu (PLN)", 0.0, step=0.01)
            n_min = st.number_input("Min. stan (Alarm)", value=5)

        if st.form_submit_button("Zapisz w bazie"):
            if n_nazwa:
                ok, msg = dodaj_produkt(n_nazwa, n_kat, n_opis, n_ilosc, n_cena, n_min)
                if ok: st.success(msg); st.rerun()
                else: st.error(msg)
            else:
                st.warning("Nazwa jest wymagana.")