# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4ENDIFbsoJBLHzLlratmL55rUyzdI4s
"""

import streamlit as st
from supabase import create_client
from postgrest.exceptions import APIError

# --- KONFIGURACJA ---
try:
    url = st.secrets["SUPABASE_URL"]
    key = st.secrets["SUPABASE_KEY"]
except FileNotFoundError:
    st.error("Brak kluczy API w pliku secrets!")
    st.stop()

@st.cache_resource
def init_connection():
    return create_client(url, key)

supabase = init_connection()

# --- FUNKCJE BAZY DANYCH ---

def pobierz_magazyn():
    """Pobiera wszystkie produkty posortowane po ID."""
    try:
        response = supabase.table('magazyn').select("*").order('id').execute()
        return response.data
    except APIError as e:
        st.error(f"Błąd pobierania danych: {e.message}")
        return []

def dodaj_nowy_produkt(nazwa, kategoria, opis, ilosc_startowa):
    """Dodaje nowy produkt. Zwraca True jeśli się udało."""
    dane = {
        "nazwa": str(nazwa),         # Wymuszamy format tekstu
        "kategoria": str(kategoria), # Wymuszamy format tekstu
        "opis": str(opis),           # Wymuszamy format tekstu
        "ilosc": int(ilosc_startowa) # Wymuszamy liczbę całkowitą
    }
    try:
        supabase.table('magazyn').insert(dane).execute()
        return True, "Dodano produkt."
    except APIError as e:
        # Tutaj wyłapiemy błędy typów danych (np. jeśli kolumna w bazie nadal jest zła)
        return False, f"Błąd bazy danych: {e.message} (Kod: {e.code})"

def aktualizuj_stan(id_produktu, zmiana):
    """Aktualizuje ilość sztuk dla danego ID."""
    try:
        # 1. Pobierz obecną ilość
        response = supabase.table('magazyn').select("ilosc").eq("id", id_produktu).single().execute()

        if not response.data:
            return False, "Nie znaleziono produktu."

        obecna_ilosc = response.data.get('ilosc', 0)
        nowa_ilosc = obecna_ilosc + zmiana

        if nowa_ilosc < 0:
            return False, "Nie można wydać więcej towaru niż jest w magazynie!"

        # 2. Zapisz nową ilość
        supabase.table('magazyn').update({"ilosc": int(nowa_ilosc)}).eq("id", id_produktu).execute()
        return True, f"Zaktualizowano stan. Nowa ilość: {nowa_ilosc}"

    except APIError as e:
        return False, f"Wystąpił błąd: {e.message}"

# --- INTERFEJS APLIKACJI (GUI) ---

st.set_page_config(page_title="Magazyn Cloud", page_icon="📦")
st.title("📦 System Magazynowy")

# Zakładki
tab1, tab2, tab3 = st.tabs(["📊 Stan Magazynu", "➕ Dodaj Nowy Produkt", "🔄 Dostawa / Wydanie"])

# --- ZAKŁADKA 1: TABELA ---
with tab1:
    st.header("Lista produktów")
    dane = pobierz_magazyn()

    if dane:
        # Konfiguracja wyświetlania tabeli
        st.dataframe(
            dane,
            column_order=("id", "nazwa", "ilosc", "kategoria", "opis"),
            use_container_width=True,
            hide_index=True
        )
    else:
        st.info("Brak towarów w bazie. Przejdź do zakładki 'Dodaj Nowy Produkt'.")

# --- ZAKŁADKA 2: NOWY PRODUKT ---
with tab2:
    st.header("Tworzenie kartoteki")
    with st.form("formularz_dodawania"):
        col1, col2 = st.columns(2)

        with col1:
            input_nazwa = st.text_input("Nazwa produktu (np. Chleb)")
            input_kategoria = st.selectbox("Kategoria", ["Spożywcze", "Elektronika", "Chemia", "Odzież", "Inne"])

        with col2:
            input_ilosc = st.number_input("Ilość początkowa", min_value=0, step=1, value=0)
            input_opis = st.text_area("Opis / Uwagi")

        submit = st.form_submit_button("Zapisz w bazie")

        if submit:
            if input_nazwa:
                sukces, wiadomosc = dodaj_nowy_produkt(input_nazwa, input_kategoria, input_opis, input_ilosc)
                if sukces:
                    st.success(f"Sukces: {input_nazwa} został dodany!")
                    # Rerun odświeża tabelę w pierwszej zakładce
                    st.rerun()
                else:
                    st.error(wiadomosc)
            else:
                st.warning("Musisz podać nazwę produktu!")

# --- ZAKŁADKA 3: ZMIANA STANU ---
with tab3:
    st.header("Operacje magazynowe")
    lista = pobierz_magazyn()

    if lista:
        # Tworzymy listę wyboru: "Chleb (ID: 5) - Stan: 10"
        opcje = {f"{p['nazwa']} (ID: {p['id']}) | Stan: {p['ilosc']}": p['id'] for p in lista}

        wybrana_etykieta = st.selectbox("Wybierz towar:", options=list(opcje.keys()))
        wybrane_id = opcje[wybrana_etykieta]

        c1, c2 = st.columns(2)

        # Sekcja Dostawy
        with c1:
            st.info("📥 Dostawa")
            ile_dodac = st.number_input("Ile przyjąć?", min_value=1, step=1, key="dostawa")
            if st.button("Zatwierdź dostawę"):
                ok, msg = aktualizuj_stan(wybrane_id, ile_dodac)
                if ok:
                    st.success(msg)
                    st.rerun()
                else:
                    st.error(msg)

        # Sekcja Wydania
        with c2:
            st.error("📤 Wydanie")
            ile_odjac = st.number_input("Ile wydać?", min_value=1, step=1, key="wydanie")
            if st.button("Zatwierdź wydanie"):
                ok, msg = aktualizuj_stan(wybrane_id, -ile_odjac) # Przekazujemy liczbę ujemną
                if ok:
                    st.success(msg)
                    st.rerun()
                else:
                    st.error(msg)
    else:
        st.warning("Najpierw dodaj produkty do bazy.")