# -*- coding: utf-8 -*-
"""mikolaj1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SacM_H14jdQ93EJRN4Y4KZtv-WCy89bC
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches

# --- Konfiguracja strony Streamlit ---
st.set_page_config(page_title="Mikołaj w Streamlit", page_icon="🎅")

st.title("🎅 Ho Ho Ho! Mikołaj wygenerowany w Pythonie")
st.markdown("Ten rysunek został stworzony w 100% przy użyciu kodu i biblioteki `matplotlib`.")

# --- Opcjonalnie: Interaktywność (np. zmiana koloru tła w pasku bocznym) ---
bg_color = st.sidebar.color_picker("Wybierz kolor tła wykresu", "#FFFFFF")

# --- Konfiguracja płótna Matplotlib ---
# Tworzymy figurę
fig, ax = plt.subplots(figsize=(6, 10))
fig.patch.set_facecolor(bg_color) # Ustawienie koloru tła figury
ax.set_facecolor(bg_color)        # Ustawienie koloru tła osi

# Ustawiamy zakresy osi
ax.set_xlim(0, 100)
ax.set_ylim(-50, 130)
ax.set_aspect('equal')
ax.axis('off')

# --- Definiowanie kolorów ---
SKIN_COLOR = '#FFDFC4'
BEARD_COLOR = 'white'
HAT_COLOR = 'crimson'
NOSE_COLOR = 'red'
BELT_COLOR = 'black'
BUCKLE_COLOR = 'gold'
BOOT_COLOR = 'black'

# --- RYSOWANIE ELEMENTÓW (Twoja logika rysowania) ---

# --- WARSTWA -2: NOGI I RĘCE ---
leg_left = patches.Rectangle((38, -30), 10, 30, color=HAT_COLOR, zorder=-2)
leg_right = patches.Rectangle((52, -30), 10, 30, color=HAT_COLOR, zorder=-2)
ax.add_patch(leg_left)
ax.add_patch(leg_right)

arm_left = patches.Ellipse((25, 25), 35, 12, angle=30, color=HAT_COLOR, zorder=-2)
arm_right = patches.Ellipse((75, 25), 35, 12, angle=-30, color=HAT_COLOR, zorder=-2)
ax.add_patch(arm_left)
ax.add_patch(arm_right)

mitten_left = patches.Circle((12, 18), 6, color=BOOT_COLOR, zorder=-2)
mitten_right = patches.Circle((88, 18), 6, color=BOOT_COLOR, zorder=-2)
ax.add_patch(mitten_left)
ax.add_patch(mitten_right)

# --- WARSTWA -1: BUTY ---
boot_left = patches.FancyBboxPatch((36, -45), 14, 15, boxstyle="round,pad=0.1", color=BOOT_COLOR, zorder=-1)
boot_right = patches.FancyBboxPatch((50, -45), 14, 15, boxstyle="round,pad=0.1", color=BOOT_COLOR, zorder=-1)
ax.add_patch(boot_left)
ax.add_patch(boot_right)

# --- WARSTWA 0: TUŁÓW I PAS ---
body = patches.Ellipse((50, 15), 70, 65, color=HAT_COLOR, zorder=0)
ax.add_patch(body)

belt = patches.Rectangle((20, 12), 60, 8, color=BELT_COLOR, zorder=0.1)
ax.add_patch(belt)

buckle_outer = patches.Rectangle((46, 11), 8, 10, color=BUCKLE_COLOR, zorder=0.2)
buckle_inner = patches.Rectangle((48, 13), 4, 6, color=BELT_COLOR, zorder=0.3)
ax.add_patch(buckle_outer)
ax.add_patch(buckle_inner)

# --- WARSTWA 1-6: GŁOWA ---
beard = patches.Ellipse((50, 50), 50, 60, angle=0, color=BEARD_COLOR, zorder=1)
ax.add_patch(beard)

face = patches.Circle((50, 65), 15, color=SKIN_COLOR, zorder=2)
ax.add_patch(face)

hat_triangle_coords = [[30, 75], [70, 75], [50, 115]]
hat_main = patches.Polygon(hat_triangle_coords, closed=True, color=HAT_COLOR, zorder=3)
ax.add_patch(hat_main)

hat_trim = patches.FancyBboxPatch((30, 73), 40, 8, boxstyle="round,pad=0.2", color=BEARD_COLOR, zorder=4)
ax.add_patch(hat_trim)

pom_pom = patches.Circle((50, 115), 5, color=BEARD_COLOR, zorder=4)
ax.add_patch(pom_pom)

eye_left = patches.Circle((43, 70), 2, color='black', zorder=5)
eye_right = patches.Circle((57, 70), 2, color='black', zorder=5)
ax.add_patch(eye_left)
ax.add_patch(eye_right)

nose = patches.Circle((50, 63), 4, color=NOSE_COLOR, zorder=6)
ax.add_patch(nose)

smile = patches.Wedge((50, 63), 10, 210, 330, width=1, color='black', alpha=0.5, zorder=5)
ax.add_patch(smile)

# --- WYŚWIETLANIE W STREAMLIT ---
# To jest kluczowa zmiana względem zwykłego Pythona/Colab
st.pyplot(fig)